package com.unicauca.edu.co.openmarket.client.presentation.users;

import com.unicauca.edu.co.openmarket.client.access.ProductAccessImplSockets;
import com.unicauca.edu.co.openmarket.client.commands.OMInvoker;
import com.unicauca.edu.co.openmarket.commons.domain.Product;
import javax.swing.JOptionPane;
import javax.swing.*;
import reloj.frameworkobsobs.Observador;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import reloj.frameworkobsobs.Observador;
import com.unicauca.edu.co.openmarket.client.presentation.products.GUIConfirmedProduct;


/**
 *
 * @author Julian
 */
public class GUIBuy extends javax.swing.JFrame implements Observador{

    private ProductAccessImplSockets productAccess;
    private Product purchasedProduct;
    
    private OMInvoker ominvoker;
    private JFrame frame;
   // JLabel etiquetaProducto = new JLabel();

    /**
     * Creates new form GUIProducts
     */
    public GUIBuy(GUIBuyer aThis, boolean par, ProductAccessImplSockets productAccess, Product purchasedProduct) {
        initComponents();
        productAccess = new ProductAccessImplSockets();
        this.purchasedProduct = purchasedProduct;
        ominvoker = new OMInvoker();
        setLocationRelativeTo(null);

    }

    public ProductAccessImplSockets getProductAccess() {
        return productAccess;
    }

    public void setProductAccess(ProductAccessImplSockets productAccess) {
        this.productAccess = productAccess;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlSouth = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Productos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("¿Como quieres pagar?");

        javax.swing.GroupLayout pnlNorthLayout = new javax.swing.GroupLayout(pnlNorth);
        pnlNorth.setLayout(pnlNorthLayout);
        pnlNorthLayout.setHorizontalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNorthLayout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );
        pnlNorthLayout.setVerticalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Selecciona el tipo de Tarjeta");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ","Visa", "Mastercard", "PSE" }));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3))
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pnlSouth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlSouth.setAlignmentX(1.5F);
        pnlSouth.setAlignmentY(5.0F);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSouthLayout = new javax.swing.GroupLayout(pnlSouth);
        pnlSouth.setLayout(pnlSouthLayout);
        pnlSouthLayout.setHorizontalGroup(
            pnlSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSouthLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(btnCerrar))
        );
        pnlSouthLayout.setVerticalGroup(
            pnlSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSouthLayout.createSequentialGroup()
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIBuy(this, true, productAccess).setVisible(true);
            }
        });*/
    }

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
                String selectedOption = (String) jComboBox1.getSelectedItem();
                if (selectedOption.equals("Visa")) {
                    showMenuOption();
                } else if (selectedOption.equals("Mastercard")) {
                    showMenuOption();
                } else if (selectedOption.equals("PSE")) {
                    showMenuOption3();
                }
    }//GEN-LAST:event_jButton1ActionPerformed
    
     private void showMenuOption() {

        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(10, 10));

        JLabel lblNumeroTarjeta = new JLabel("Número de Tarjeta:");
        JTextField txtNumeroTarjeta = new JTextField();

        JLabel lblFechaVencimiento = new JLabel("Fecha de Vencimiento:");
        JTextField txtFechaVencimiento = new JTextField();

        JLabel lblCodigoSeguridad = new JLabel("Codigo de Seguridad:");
        JTextField txtCodigoSeguridad = new JTextField();

        JLabel lblNombreTitular = new JLabel("Nombre del Titular:");
        JTextField txtNombreTitular = new JTextField();

        JLabel lblDireccionFact = new JLabel("Direccion de Facturación:");
        JTextField txtDireccionFact = new JTextField();

        panel.add(lblNumeroTarjeta);
        panel.add(txtNumeroTarjeta);
        panel.add(lblFechaVencimiento);
        panel.add(txtFechaVencimiento); 
        panel.add(lblCodigoSeguridad);
        panel.add(txtCodigoSeguridad);
        panel.add(lblNombreTitular);
        panel.add(txtNombreTitular);
        panel.add(lblDireccionFact);
        panel.add(txtDireccionFact);
    

     int result = JOptionPane.showConfirmDialog(frame, panel, "Ingrese los datos", JOptionPane.OK_CANCEL_OPTION);

     if (result == JOptionPane.OK_OPTION) {
         String numeroTarjeta = txtNumeroTarjeta.getText();
         String FechaVencimiento = txtFechaVencimiento.getText();
         String CodigoSeguridad = txtCodigoSeguridad.getText();
         String nombreTitular = txtNombreTitular.getText();
         String DireccionFact = txtDireccionFact.getText();
         

         if (numeroTarjeta.isEmpty() || FechaVencimiento.isEmpty() || CodigoSeguridad.isEmpty() || nombreTitular.isEmpty() || DireccionFact.isEmpty()) {
             JOptionPane.showMessageDialog(frame, "Debe completar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
             showMenuOption(); // Vuelve a llamar al método para mostrar el cuadro de diálogo nuevamente
         } else {
             String mensaje = "Número de tarjeta: " + numeroTarjeta  + "\n Fecha de Vencimiento: " + FechaVencimiento + "\n Codigo de Seguridad: "+CodigoSeguridad+ "\n Nombre del titular: " +nombreTitular
                 + "\n Direccion de Facturacion: " +DireccionFact;
             JOptionPane.showMessageDialog(frame, mensaje);
              
            }
         Buyproduct();
        }
    }
    private void showMenuOption3() {
       JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(10, 10));

        JLabel lblBanco = new JLabel("Banco:");
        JTextField txtBanco = new JTextField();

        JLabel lblTipoCuenta = new JLabel("Tipo de Cuenta");
        JTextField txtTipoCuenta = new JTextField();

        JLabel lblNumeroCuenta = new JLabel("Numero de cuenta:");
        JTextField txtNumeroCuenta = new JTextField();

        JLabel lblNumeroId = new JLabel("Numero de identificacion");
        JTextField txtNumeroId = new JTextField();

        JLabel lblNombres = new JLabel("Nombre y Apellido");
        JTextField txtNombres = new JTextField();
        
        JLabel lblCorreoElec = new JLabel("Correo electronico:");
        JTextField txtCorreoElec = new JTextField();
        
        JLabel lblTel = new JLabel("Telefono de contacto:");
        JTextField txtTel = new JTextField();


        panel.add(lblBanco);
        panel.add(txtBanco);
        panel.add(lblTipoCuenta);
        panel.add(txtTipoCuenta); 
        panel.add(lblNumeroCuenta);
        panel.add(txtNumeroCuenta);
        panel.add(lblNumeroId);
        panel.add(txtNumeroId);
        panel.add(lblNombres);
        panel.add(txtNombres);
        panel.add(lblCorreoElec);
        panel.add(txtCorreoElec);
        panel.add(lblTel);
        panel.add(txtTel);
    

     int result = JOptionPane.showConfirmDialog(frame, panel, "Ingrese los datos", JOptionPane.OK_CANCEL_OPTION);

     if (result == JOptionPane.OK_OPTION) {
         String Banco = txtBanco.getText();
         String TipoCuenta = txtTipoCuenta.getText();
         String NumeroCuenta  = txtNumeroCuenta.getText();
         String NumeroId = txtNumeroId.getText();
         String Nombres = txtNombres.getText();
         String CorreoElec = txtCorreoElec.getText();
         String Tel = txtTel.getText();
         

         if (Banco.isEmpty() || TipoCuenta.isEmpty() || NumeroCuenta.isEmpty() || NumeroId.isEmpty() || Nombres.isEmpty() || CorreoElec.isEmpty()|| Tel.isEmpty()) {
             JOptionPane.showMessageDialog(frame, "Debe completar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
             showMenuOption3(); // Vuelve a llamar al método para mostrar el cuadro de diálogo nuevamente
         } else {
             String mensaje = "Banco: " + Banco  + "\n Tipo de Cuenta: " + TipoCuenta + "\n Numero de Cuenta: "+NumeroCuenta+ "\n Numero de identificación: " +NumeroId
                 + "\n Nombres y Apellidos " +Nombres+ "\n Correo Electronivo " +CorreoElec +"\n Telefono: ";
             JOptionPane.showMessageDialog(frame, mensaje);
              
            }
         Buyproduct();
        }
     
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JPanel pnlSouth;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void Buyproduct() {
            JFrame productFrame = new JFrame("Detalles del Producto");
            productFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            JPanel productPanel = new JPanel();
            productPanel.setLayout(new GridBagLayout()); // Utilizamos GridBagLayout

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.anchor = GridBagConstraints.WEST;
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.insets = new Insets(5, 5, 5, 5);

            JLabel nameLabel = new JLabel("Producto:");
            productPanel.add(nameLabel, gbc);

            gbc.gridx = 1;
            JLabel nameValueLabel = new JLabel(purchasedProduct.getName());
            productPanel.add(nameValueLabel, gbc);

            gbc.gridx = 0;
            gbc.gridy = 1;
            JLabel descriptionLabel = new JLabel("Descripción:");
            productPanel.add(descriptionLabel, gbc);

            gbc.gridx = 1;
            JLabel descriptionValueLabel = new JLabel(purchasedProduct.getDescription());
            productPanel.add(descriptionValueLabel, gbc);

            gbc.gridx = 0;
            gbc.gridy = 2;
            JLabel priceLabel = new JLabel("Precio:");
            productPanel.add(priceLabel, gbc);

            gbc.gridx = 1;
            JLabel priceValueLabel = new JLabel(String.valueOf(purchasedProduct.getPrice()));
            productPanel.add(priceValueLabel, gbc);

            gbc.gridx = 0;
            gbc.gridy = 3;
            gbc.gridwidth = 2;
            gbc.anchor = GridBagConstraints.CENTER;
            JButton calificarButton = new JButton("Calificar");
            productPanel.add(calificarButton, gbc);

            calificarButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    /*GUIConfirmedProduct instance = new GUIConfirmedProduct(purchasedProduct);
                    instance.setVisible(true);
                    productAccess.addObservador((Observador) instance);*/
                    productFrame.dispose();
                }
            });

            productFrame.getContentPane().add(productPanel);

            // Ajustar el tamaño de la ventana
            productFrame.setSize(400, 300); // Establece el ancho y alto deseado

            productFrame.setLocationRelativeTo(null);
            productFrame.setVisible(true);
        }
    
}
